/**
 * Скрипт для создания 20 тестовых пользователей в базе данных
 * Запуск: node scripts/seedTestUsers.js
 */

const mongoose = require('mongoose');
const User = require('../models/userModel');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/users';

// Фото реальных людей — randomuser.me (стабильные, без expiry)
const wp = (n) => ({ url: `https://randomuser.me/api/portraits/women/${n}.jpg`, key: null, status: 'approved', format: 'jpg' });
const mp = (n) => ({ url: `https://randomuser.me/api/portraits/men/${n}.jpg`,   key: null, status: 'approved', format: 'jpg' });

const INTERESTS = [
  'Путешествия', 'Кино', 'Музыка', 'Спорт', 'Готовка', 'Чтение',
  'Фотография', 'Танцы', 'Йога', 'Искусство', 'Игры', 'Природа',
  'Фитнес', 'Кофе', 'Животные', 'Театр', 'Велосипед', 'Плавание',
];

const LOCATIONS = [
  'Москва', 'Санкт-Петербург', 'Казань', 'Новосибирск', 'Екатеринбург',
  'Нижний Новгород', 'Краснодар', 'Ростов-на-Дону', 'Самара', 'Уфа',
];

const ZODIACS = [
  'Овен', 'Телец', 'Близнецы', 'Рак', 'Лев', 'Дева',
  'Весы', 'Скорпион', 'Стрелец', 'Козерог', 'Водолей', 'Рыбы',
];

const EDUCATION = [
  'Высшее', 'Неоконченное высшее', 'Среднее специальное', 'Магистратура', 'Аспирантура',
];

const WORK = [
  'Дизайнер', 'Программист', 'Маркетолог', 'Врач', 'Учитель',
  'Предприниматель', 'Менеджер', 'Журналист', 'Фотограф', 'Архитектор',
];

const LOOKING_FOR_OPTIONS = [
  { id: 'relationship', title: 'Отношения',       icon: 'rose-outline'   },
  { id: 'friendship',   title: 'Дружба',           icon: 'happy-outline'  },
  { id: 'dating',       title: 'Свидания',         icon: 'wine-outline'   },
  { id: 'marriage',     title: 'Создание семьи',   icon: 'home-outline'   },
];

const rand = (arr) => arr[Math.floor(Math.random() * arr.length)];
const randN = (arr, n) => [...arr].sort(() => Math.random() - 0.5).slice(0, n);
const randInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;

const testUsers = [
  // === ЖЕНЩИНЫ ===
  {
    name: 'Анастасия',
    age: 24,
    gender: { id: 'female', title: 'Женский' },
    wishUser: 'male',
    userSex: 'heterosexual',
    userLocation: 'Москва',
    about: 'Люблю путешествовать и открывать новые места. Обожаю кофе и хорошие книги 📚',
    work: 'Дизайнер',
    education: 'Высшее',
    zodiac: 'Дева',
    relationship: 'Свободна',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Иногда',
    languages: ['Русский', 'Английский'],
    pets: ['Кошка'],
    interests: ['Путешествия', 'Фотография', 'Кофе', 'Кино'],
    lookingFor: { id: 'relationship', title: 'Отношения', icon: 'rose-outline' },
    userPhoto: [wp(1), wp(2), wp(3), wp(26), wp(27), wp(28), wp(29), wp(30), wp(31), wp(32)],
  },
  {
    name: 'Мария',
    age: 27,
    gender: { id: 'female', title: 'Женский' },
    wishUser: 'male',
    userSex: 'heterosexual',
    userLocation: 'Санкт-Петербург',
    about: 'Врач по профессии, путешественник по призванию 🌍 Ищу того, кто не боится приключений',
    work: 'Врач',
    education: 'Высшее',
    zodiac: 'Телец',
    relationship: 'Свободна',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Нет',
    languages: ['Русский', 'Английский', 'Немецкий'],
    pets: [],
    interests: ['Путешествия', 'Спорт', 'Йога', 'Чтение'],
    lookingFor: { id: 'relationship', title: 'Отношения', icon: 'rose-outline' },
    userPhoto: [wp(4), wp(5), wp(33), wp(34), wp(35), wp(36), wp(37), wp(38), wp(39), wp(40)],
  },
  {
    name: 'Екатерина',
    age: 22,
    gender: { id: 'female', title: 'Женский' },
    wishUser: 'male',
    userSex: 'heterosexual',
    userLocation: 'Казань',
    about: 'Студентка последнего курса. Танцую, рисую, мечтаю 🎨',
    work: 'Студент',
    education: 'Неоконченное высшее',
    zodiac: 'Рыбы',
    relationship: 'Свободна',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Иногда',
    languages: ['Русский', 'Английский'],
    pets: ['Собака'],
    interests: ['Танцы', 'Искусство', 'Музыка', 'Животные'],
    lookingFor: { id: 'dating', title: 'Свидания', icon: 'wine-outline' },
    userPhoto: [wp(6), wp(7), wp(8), wp(41), wp(42), wp(43), wp(44), wp(45), wp(46), wp(47)],
  },
  {
    name: 'Юлия',
    age: 29,
    gender: { id: 'female', title: 'Женский' },
    wishUser: 'male',
    userSex: 'heterosexual',
    userLocation: 'Екатеринбург',
    about: 'Маркетолог. Обожаю кофе, горы и хорошие разговоры ☕🏔️',
    work: 'Маркетолог',
    education: 'Высшее',
    zodiac: 'Лев',
    relationship: 'Свободна',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Иногда',
    languages: ['Русский', 'Английский'],
    pets: [],
    interests: ['Путешествия', 'Фитнес', 'Кофе', 'Природа'],
    lookingFor: { id: 'relationship', title: 'Отношения', icon: 'rose-outline' },
    userPhoto: [wp(9), wp(10), wp(48), wp(49), wp(50), wp(51), wp(52), wp(53), wp(54), wp(55)],
  },
  {
    name: 'Ольга',
    age: 31,
    gender: { id: 'female', title: 'Женский' },
    wishUser: 'male',
    userSex: 'heterosexual',
    userLocation: 'Москва',
    about: 'Предприниматель. Люблю театр, вино и интересных людей 🍷',
    work: 'Предприниматель',
    education: 'Высшее',
    zodiac: 'Скорпион',
    relationship: 'Свободна',
    children: 'Есть (1)',
    smoking: 'Нет',
    alcohol: 'Иногда',
    languages: ['Русский', 'Французский', 'Английский'],
    pets: ['Кошка'],
    interests: ['Театр', 'Кино', 'Путешествия', 'Чтение'],
    lookingFor: { id: 'marriage', title: 'Создание семьи', icon: 'home-outline' },
    userPhoto: [wp(11), wp(12), wp(13), wp(56), wp(57), wp(58), wp(59), wp(60), wp(61), wp(62)],
  },
  {
    name: 'Дарья',
    age: 25,
    gender: { id: 'female', title: 'Женский' },
    wishUser: 'all',
    userSex: 'bisexual',
    userLocation: 'Санкт-Петербург',
    about: 'Фотограф и путешественник. Снимаю людей и природу 📸',
    work: 'Фотограф',
    education: 'Среднее специальное',
    zodiac: 'Близнецы',
    relationship: 'Свободна',
    children: 'Нет',
    smoking: 'Иногда',
    alcohol: 'Иногда',
    languages: ['Русский', 'Английский'],
    pets: [],
    interests: ['Фотография', 'Путешествия', 'Природа', 'Искусство'],
    lookingFor: { id: 'friendship', title: 'Дружба', icon: 'happy-outline' },
    userPhoto: [wp(14), wp(15), wp(63), wp(64), wp(65), wp(66), wp(67), wp(68), wp(69), wp(70)],
  },
  {
    name: 'Валерия',
    age: 23,
    gender: { id: 'female', title: 'Женский' },
    wishUser: 'male',
    userSex: 'heterosexual',
    userLocation: 'Краснодар',
    about: 'Люблю море, солнце и позитивных людей ☀️🌊',
    work: 'Менеджер',
    education: 'Высшее',
    zodiac: 'Рак',
    relationship: 'Свободна',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Иногда',
    languages: ['Русский'],
    pets: ['Собака'],
    interests: ['Плавание', 'Фитнес', 'Кино', 'Готовка'],
    lookingFor: { id: 'dating', title: 'Свидания', icon: 'wine-outline' },
    userPhoto: [wp(16), wp(17), wp(18), wp(71), wp(72), wp(73), wp(74), wp(75), wp(76), wp(77)],
  },
  {
    name: 'Алина',
    age: 26,
    gender: { id: 'female', title: 'Женский' },
    wishUser: 'male',
    userSex: 'heterosexual',
    userLocation: 'Новосибирск',
    about: 'Программистка. Днём пишу код, вечером читаю книги 💻📖',
    work: 'Программист',
    education: 'Высшее',
    zodiac: 'Водолей',
    relationship: 'Свободна',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Нет',
    languages: ['Русский', 'Английский'],
    pets: ['Кошка'],
    interests: ['Игры', 'Чтение', 'Кино', 'Кофе'],
    lookingFor: { id: 'relationship', title: 'Отношения', icon: 'rose-outline' },
    userPhoto: [wp(19), wp(20), wp(78), wp(79), wp(80), wp(81), wp(82), wp(83), wp(84), wp(85)],
  },
  {
    name: 'Анна',
    age: 28,
    gender: { id: 'female', title: 'Женский' },
    wishUser: 'male',
    userSex: 'heterosexual',
    userLocation: 'Москва',
    about: 'Архитектор. Вижу красоту в деталях и людях 🏛️',
    work: 'Архитектор',
    education: 'Магистратура',
    zodiac: 'Овен',
    relationship: 'Свободна',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Иногда',
    languages: ['Русский', 'Английский', 'Итальянский'],
    pets: [],
    interests: ['Искусство', 'Путешествия', 'Фотография', 'Театр'],
    lookingFor: { id: 'marriage', title: 'Создание семьи', icon: 'home-outline' },
    userPhoto: [wp(21), wp(22), wp(23), wp(86), wp(87), wp(88), wp(89), wp(90), wp(91), wp(92)],
  },
  {
    name: 'Полина',
    age: 21,
    gender: { id: 'female', title: 'Женский' },
    wishUser: 'male',
    userSex: 'heterosexual',
    userLocation: 'Ростов-на-Дону',
    about: 'Студентка медицины. Йога, правильное питание и мечты о путешествиях 🧘‍♀️',
    work: 'Студент',
    education: 'Неоконченное высшее',
    zodiac: 'Козерог',
    relationship: 'Свободна',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Нет',
    languages: ['Русский', 'Английский'],
    pets: [],
    interests: ['Йога', 'Путешествия', 'Спорт', 'Природа'],
    lookingFor: { id: 'dating', title: 'Свидания', icon: 'wine-outline' },
    userPhoto: [wp(24), wp(25), wp(93), wp(94), wp(95), wp(96), wp(97), wp(98), wp(99), wp(0)],
  },

  // === МУЖЧИНЫ ===
  {
    name: 'Александр',
    age: 28,
    gender: { id: 'male', title: 'Мужской' },
    wishUser: 'female',
    userSex: 'heterosexual',
    userLocation: 'Москва',
    about: 'IT-предприниматель. Люблю горы, сноуборд и хорошее кино 🏔️🎬',
    work: 'Предприниматель',
    education: 'Высшее',
    zodiac: 'Стрелец',
    relationship: 'Свободен',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Иногда',
    languages: ['Русский', 'Английский'],
    pets: ['Собака'],
    interests: ['Путешествия', 'Спорт', 'Кино', 'Природа'],
    lookingFor: { id: 'relationship', title: 'Отношения', icon: 'rose-outline' },
    userPhoto: [mp(1), mp(2), mp(3), mp(26), mp(27), mp(28), mp(29), mp(30), mp(31), mp(32)],
  },
  {
    name: 'Дмитрий',
    age: 32,
    gender: { id: 'male', title: 'Мужской' },
    wishUser: 'female',
    userSex: 'heterosexual',
    userLocation: 'Санкт-Петербург',
    about: 'Журналист и писатель. Интересуюсь историей, философией и хорошей едой 📝',
    work: 'Журналист',
    education: 'Высшее',
    zodiac: 'Весы',
    relationship: 'Свободен',
    children: 'Нет',
    smoking: 'Иногда',
    alcohol: 'Иногда',
    languages: ['Русский', 'Английский', 'Французский'],
    pets: [],
    interests: ['Чтение', 'Театр', 'Кино', 'Готовка'],
    lookingFor: { id: 'relationship', title: 'Отношения', icon: 'rose-outline' },
    userPhoto: [mp(4), mp(5), mp(33), mp(34), mp(35), mp(36), mp(37), mp(38), mp(39), mp(40)],
  },
  {
    name: 'Иван',
    age: 25,
    gender: { id: 'male', title: 'Мужской' },
    wishUser: 'female',
    userSex: 'heterosexual',
    userLocation: 'Екатеринбург',
    about: 'Инженер. В свободное время занимаюсь велоспортом и фотографией 🚴',
    work: 'Программист',
    education: 'Высшее',
    zodiac: 'Дева',
    relationship: 'Свободен',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Нет',
    languages: ['Русский', 'Английский'],
    pets: [],
    interests: ['Велосипед', 'Фотография', 'Природа', 'Спорт'],
    lookingFor: { id: 'dating', title: 'Свидания', icon: 'wine-outline' },
    userPhoto: [mp(6), mp(7), mp(8), mp(41), mp(42), mp(43), mp(44), mp(45), mp(46), mp(47)],
  },
  {
    name: 'Михаил',
    age: 30,
    gender: { id: 'male', title: 'Мужской' },
    wishUser: 'female',
    userSex: 'heterosexual',
    userLocation: 'Казань',
    about: 'Врач-хирург. Серьёзный на работе, весёлый в жизни 😄',
    work: 'Врач',
    education: 'Высшее',
    zodiac: 'Телец',
    relationship: 'Свободен',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Нет',
    languages: ['Русский', 'Английский'],
    pets: [],
    interests: ['Спорт', 'Кино', 'Путешествия', 'Готовка'],
    lookingFor: { id: 'marriage', title: 'Создание семьи', icon: 'home-outline' },
    userPhoto: [mp(9), mp(10), mp(48), mp(49), mp(50), mp(51), mp(52), mp(53), mp(54), mp(55)],
  },
  {
    name: 'Артём',
    age: 23,
    gender: { id: 'male', title: 'Мужской' },
    wishUser: 'all',
    userSex: 'bisexual',
    userLocation: 'Москва',
    about: 'Музыкант и диджей. Живу ночной жизнью и создаю музыку 🎵',
    work: 'Музыкант',
    education: 'Среднее специальное',
    zodiac: 'Близнецы',
    relationship: 'Свободен',
    children: 'Нет',
    smoking: 'Иногда',
    alcohol: 'Иногда',
    languages: ['Русский', 'Английский'],
    pets: [],
    interests: ['Музыка', 'Танцы', 'Кино', 'Искусство'],
    lookingFor: { id: 'friendship', title: 'Дружба', icon: 'happy-outline' },
    userPhoto: [mp(11), mp(12), mp(13), mp(56), mp(57), mp(58), mp(59), mp(60), mp(61), mp(62)],
  },
  {
    name: 'Никита',
    age: 27,
    gender: { id: 'male', title: 'Мужской' },
    wishUser: 'female',
    userSex: 'heterosexual',
    userLocation: 'Новосибирск',
    about: 'Занимаюсь бизнесом в сфере недвижимости. Люблю спорт и путешествия ✈️',
    work: 'Предприниматель',
    education: 'Высшее',
    zodiac: 'Лев',
    relationship: 'Свободен',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Иногда',
    languages: ['Русский', 'Английский'],
    pets: ['Собака'],
    interests: ['Спорт', 'Путешествия', 'Фитнес', 'Природа'],
    lookingFor: { id: 'relationship', title: 'Отношения', icon: 'rose-outline' },
    userPhoto: [mp(14), mp(15), mp(63), mp(64), mp(65), mp(66), mp(67), mp(68), mp(69), mp(70)],
  },
  {
    name: 'Сергей',
    age: 34,
    gender: { id: 'male', title: 'Мужской' },
    wishUser: 'female',
    userSex: 'heterosexual',
    userLocation: 'Краснодар',
    about: 'Шеф-повар. Готовлю с душой, ем с удовольствием 🍳',
    work: 'Повар',
    education: 'Среднее специальное',
    zodiac: 'Рак',
    relationship: 'Свободен',
    children: 'Есть (2)',
    smoking: 'Нет',
    alcohol: 'Иногда',
    languages: ['Русский'],
    pets: ['Кошка'],
    interests: ['Готовка', 'Путешествия', 'Спорт', 'Природа'],
    lookingFor: { id: 'marriage', title: 'Создание семьи', icon: 'home-outline' },
    userPhoto: [mp(16), mp(17), mp(18), mp(71), mp(72), mp(73), mp(74), mp(75), mp(76), mp(77)],
  },
  {
    name: 'Владимир',
    age: 29,
    gender: { id: 'male', title: 'Мужской' },
    wishUser: 'female',
    userSex: 'heterosexual',
    userLocation: 'Самара',
    about: 'Архитектор. Создаю пространства для жизни и мечтаю об идеальном городе 🏙️',
    work: 'Архитектор',
    education: 'Магистратура',
    zodiac: 'Козерог',
    relationship: 'Свободен',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Иногда',
    languages: ['Русский', 'Английский'],
    pets: [],
    interests: ['Искусство', 'Путешествия', 'Велосипед', 'Фотография'],
    lookingFor: { id: 'relationship', title: 'Отношения', icon: 'rose-outline' },
    userPhoto: [mp(19), mp(20), mp(78), mp(79), mp(80), mp(81), mp(82), mp(83), mp(84), mp(85)],
  },
  {
    name: 'Роман',
    age: 26,
    gender: { id: 'male', title: 'Мужской' },
    wishUser: 'female',
    userSex: 'heterosexual',
    userLocation: 'Уфа',
    about: 'Спортсмен и тренер. ЗОЖ — это образ жизни, а не диета 💪',
    work: 'Тренер',
    education: 'Высшее',
    zodiac: 'Овен',
    relationship: 'Свободен',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Нет',
    languages: ['Русский', 'Английский'],
    pets: ['Собака'],
    interests: ['Спорт', 'Фитнес', 'Природа', 'Плавание'],
    lookingFor: { id: 'relationship', title: 'Отношения', icon: 'rose-outline' },
    userPhoto: [mp(21), mp(22), mp(23), mp(86), mp(87), mp(88), mp(89), mp(90), mp(91), mp(92)],
  },
  {
    name: 'Павел',
    age: 31,
    gender: { id: 'male', title: 'Мужской' },
    wishUser: 'female',
    userSex: 'heterosexual',
    userLocation: 'Нижний Новгород',
    about: 'Маркетолог в стартапе. Люблю горы, книги и хороший юмор 📚',
    work: 'Маркетолог',
    education: 'Высшее',
    zodiac: 'Водолей',
    relationship: 'Свободен',
    children: 'Нет',
    smoking: 'Нет',
    alcohol: 'Иногда',
    languages: ['Русский', 'Английский'],
    pets: [],
    interests: ['Чтение', 'Путешествия', 'Кино', 'Игры'],
    lookingFor: { id: 'relationship', title: 'Отношения', icon: 'rose-outline' },
    userPhoto: [mp(24), mp(25), mp(93), mp(94), mp(95), mp(96), mp(97), mp(98), mp(99), mp(0)],
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('✅ Connected to MongoDB:', MONGO_URI);

    // Удаляем старых тестовых юзеров (без email и deviceId — признак тестового)
    const names = testUsers.map((u) => u.name);
    const deleted = await User.deleteMany({
      name: { $in: names },
      email: { $exists: false },
      deviceId: { $exists: false },
    });
    console.log(`🗑️  Deleted old test users: ${deleted.deletedCount}`);

    let created = 0;

    for (const userData of testUsers) {
      // insertOne напрямую — обходим Mongoose валидацию (key/bucket required)
      await User.collection.insertOne({
        ...userData,
        onboardingComplete: true,
        isOnline: Math.random() > 0.5,
        lastSeen: new Date(Date.now() - Math.random() * 86400000),
        createdAt: new Date(),
        updatedAt: new Date(),
      });

      console.log(`✅ Created: ${userData.name}, ${userData.age}, ${userData.userLocation}`);
      created++;
    }

    console.log(`\n🎉 Done! Created: ${created}`);
    process.exit(0);
  } catch (err) {
    console.error('❌ Error:', err);
    process.exit(1);
  }
}

seed();
